// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALgCNkjo7BpIie97H5XRRk6TGw1t3wwkI',
    appId: '1:316846717237:web:e47b151583c5a410f9f47c',
    messagingSenderId: '316846717237',
    projectId: 'note-app-using-node-api',
    authDomain: 'note-app-using-node-api.firebaseapp.com',
    storageBucket: 'note-app-using-node-api.appspot.com',
    measurementId: 'G-4E5ZEQ9TD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCybBzLc_T_CrRgxcfU0yzdFRfYT0JWEk0',
    appId: '1:316846717237:android:b69f456807799eeef9f47c',
    messagingSenderId: '316846717237',
    projectId: 'note-app-using-node-api',
    storageBucket: 'note-app-using-node-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKHq9SQ2m1aAV3uOxSCIOfNmsbiblVxs',
    appId: '1:316846717237:ios:67297fc5569488bff9f47c',
    messagingSenderId: '316846717237',
    projectId: 'note-app-using-node-api',
    storageBucket: 'note-app-using-node-api.appspot.com',
    iosClientId: '316846717237-tr45pgmkmhkfculvaqpfs9sdd9g00eo8.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKHq9SQ2m1aAV3uOxSCIOfNmsbiblVxs',
    appId: '1:316846717237:ios:67297fc5569488bff9f47c',
    messagingSenderId: '316846717237',
    projectId: 'note-app-using-node-api',
    storageBucket: 'note-app-using-node-api.appspot.com',
    iosClientId: '316846717237-tr45pgmkmhkfculvaqpfs9sdd9g00eo8.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );
}
